---
title: "kenya_code"
author: "Dianovics Dominik"
date: "2023-12-15"
output:
  html_document: default
  pdf_document: default
---

```{r setup}
library(tidytuesdayR)
library(tidyverse)
library(tools)
library(stringdist)
library(fuzzyjoin)
library(patchwork)
library(knitr)
library(gt)
library(gridExtra)
library(broom)
library(lmtest)
library(robustbase)
library(MASS)
library(mediation)
library(devtools)
library(flexplot)
```

```{r data import}
data <- tt_load('2021-01-19')

gender <- data$gender
crops <- data$crops
households <- data$households
```

```{r data cleaning}
view(crops)
str(crops)

#Issue with crops, all names are caps lock

crops <- crops |> 
  mutate(
    SubCounty = str_to_lower(SubCounty),
    SubCounty = str_to_title(SubCounty)
  )

#Removed the Khat crop because I don't know what that is and there are too many missing values

crops <- crops[, !colnames(crops) %in% "Khat (Miraa)"]


view(households)
str(households)

view(gender)
str(gender)

#Issue with city naming, not consistent through datasets

crops <- crops |> 
  mutate(
    County = SubCounty,
  ) |> 
  dplyr::select(-SubCounty)


gender <- gender |> 
  mutate(
    County = ifelse(County == "Total", "Kenya", County)
  )

gender$County <- gsub(" ", "", gender$County)

households$County <- trimws(households$County)
str(households)

colnames(households)

#Function that tries to match the County names to each other by stringdist

find_best_match <- function(county, reference_counties) {
  distances <- stringdistmatrix(county, reference_counties)
  best_match_index <- which.min(distances)
  best_match <- reference_counties[best_match_index]
  return(best_match)
}

#Function had an issue with only one value, the Nairobi city, probably due to two words in the name
crops$County[crops$County == "Nairobi"] <- "Nairobi City"
crops$best_match <- sapply(crops$County, find_best_match, reference_counties = gender$County)


households$best_match <- sapply(households$County, find_best_match, reference_counties = gender$County)


merged_dataset <- left_join(crops, households, by = c("best_match" = "County")) |> 
  left_join(gender, by = c("best_match" = "County"))

# Clean up 
merged_dataset <- merged_dataset |> 
  dplyr::select(-best_match, -best_match.y)

#County in the first column
merged_dataset <- merged_dataset |> 
  dplyr::select(County, everything())

```

```{r}
#Gender in the whole of Kenya
data_kenya <- filter(merged_dataset, County == "Kenya")

data_kenya_long <- pivot_longer(data_kenya, cols = c("Male", "Female", "Intersex"), names_to = "Gender", values_to = "Count")

data_kenya_long |> 
  ggplot(aes(x = Gender, y = Count)) +
  geom_col()

#Farming production in the 5 biggest and smalles counties by production
smallest_producers <- merged_dataset |> 
  arrange(Farming) |> 
  slice_head(n = 5) |> 
  ggplot(aes(x = County, y = Farming)) +
  geom_col() +
  labs(title = "Top 5 Counties with Smallest Farming Values",
       x = "County",
       y = "Farming") + 
  ylim(0, 400000)

biggest_producers <- merged_dataset |> 
  filter(County != "Kenya") |> 
  arrange(desc(Farming)) |> 
  slice_head(n = 5) |> 
  ggplot(aes(x = County, y = Farming)) +
  geom_col() +
  labs(title = "Top 5 Counties with Biggest Farming Values",
       x = "County",
       y = "Farming") +
  ylim(0, 400000)

grid.arrange(smallest_producers, biggest_producers, ncol = 2)
```

```{r}
#Population in the 5 biggest and smalles counties

smallest_population <- merged_dataset |> 
  arrange(Population) |> 
  slice_head(n = 5) |> 
  ggplot(aes(x = County, y = Population)) +
  geom_col() +
  labs(title = "Top 5 Counties with Smallest Population",
       x = "County",
       y = "Population") + 
  ylim(0, 3000000)

biggest_population <- merged_dataset |>
  filter(County != "Kenya") |> 
  arrange(desc(Population)) |> 
  slice_head(n = 5) |> 
  ggplot(aes(x = County, y = Population)) +
  geom_col() +
  labs(title = "Top 5 Counties with Biggest Population",
       x = "County",
       y = "Population") + 
  ylim(0, 3000000)

grid.arrange(smallest_population, biggest_population, ncol = 2)
```

```{r Descriptives}

#Means
merged_dataset %>%
  summarise(
    Population = mean(Population),
    Farming = mean(Farming),
    "N of households" = mean(NumberOfHouseholds)
  ) %>%
  pivot_longer(everything(), names_to = "Variable", values_to = "Mean") %>%
  mutate(
    Mean = round(Mean, 0)
  ) |> 
  gt() %>%
  tab_header(
    title = md("**Descriptive statistics**"),
    subtitle = "Kenya census 2019"
  ) %>%
  fmt_number(
    columns = vars(Variable)
  )


#Standard deviations
merged_dataset |> 
  summarise(
    Population = sd(Population),
    Farming = sd(Farming),
    "N of households" = sd(NumberOfHouseholds)
  ) |> 
  pivot_longer(everything(), names_to = "Variable", values_to = "SD") |> 
  mutate(
    SD = round(SD, 0)
  ) |>
  gt() |> 
  tab_header(
    title = md("**Descriptive statistics**"),
    subtitle = "Kenya census 2019"
  ) |> 
  fmt_number(
    columns = c(Variable)
  )

#Outliers with boxplots

##Population
merged_dataset |> 
  filter(County != "Kenya") |> 
  ggplot(aes(x = 1, y = Population)) +
  geom_boxplot() +
  geom_text(aes(label = ifelse(Population < quantile(Population, 0.25) - 1.5 * IQR(Population) | 
                                  Population > quantile(Population, 0.75) + 1.5 * IQR(Population), County, "")),
            size = 5)
##Farming
merged_dataset |> 
  filter(County != "Kenya") |> 
  ggplot(aes(x = 1, y = Farming)) +
  geom_boxplot() +
  geom_text(aes(label = ifelse(Farming < quantile(Farming, 0.25) - 1.5 * IQR(Farming) | 
                                  Farming > quantile(Farming, 0.75) + 1.5 * IQR(Farming), County, "")),
            size = 5)
##Households
merged_dataset |>
  filter(County != "Kenya") |> 
  ggplot(aes(x = 1, y = NumberOfHouseholds)) +
  geom_boxplot() +
  geom_text(aes(label = ifelse(NumberOfHouseholds < quantile(NumberOfHouseholds, 0.25) - 1.5 * IQR(NumberOfHouseholds) | 
                                  NumberOfHouseholds > quantile(NumberOfHouseholds, 0.75) + 1.5 * IQR(NumberOfHouseholds), County, "")),
            size = 5)


#Conclusion: Even though there are three outliers, I will not remove them because they represent a natural occurence, where people congregate in urban areas, and the outliers are the biggest cities in Kenya.

#Plant production distribution

plants <- c("Tea", "Coffee", "Avocado", "Citrus", "Mango", "Coconut", "Macadamia", "Cashew Nut")

plant_colors <- c(
  Tea = "darkgreen",
  Coffee = "saddlebrown",
  Avocado = "limegreen",
  Citrus = "yellow",
  Mango = "darkorange",
  Coconut = "#d0d1e6",
  Macadamia = "darkolivegreen",
  "Cashew Nut" = "goldenrod"
)

merged_dataset |> 
  filter(County == "Kenya") |> 
  pivot_longer(cols = plants, names_to = "Crop", values_to = "Production") |> 
  ggplot(aes(x = fct_reorder(Crop, Production), y = Production)) +
  geom_bar(stat = "identity", fill = plant_colors) +
  coord_flip() +
  theme_minimal() +
  labs(
    title = "Plant production in Kenya",
    x = "Crop",
    y = "Production"
  )


```

```{r hypotheses}
#Linear regression
##H1: Does the population affect the farming production?
##H2: Is there a positive correlation between Tea and Coffee production?


#Mediation
##H3: Farming is a mediator between population and number of households

```

```{r H1, linear regression model 1}
#Does the population affect the farming production?
counties_data <- merged_dataset |> 
  filter(County != "Kenya")

cor(counties_data$Population, counties_data$Farming)

counties_data |> 
  ggplot(aes(x = Population, y = Farming)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Population and Farming Production",
    x = "Population",
    y = "Farming"
  ) +
  theme_minimal()

#Assumption 1.1: Normality



shapiro.test(counties_data$Population)
hist(counties_data$Population)
shapiro.test(counties_data$Farming)
hist(counties_data$Farming)

##Nairobi significantly alters the normality

pop_farming <- lm(Farming ~ Population, data = counties_data)
glance(pop_farming)

#Assumption 1.2: Linearity

raintest(pop_farming)

##Shows nonlinearity

#Assumption 1.3: Homoscedasticity

bptest(pop_farming)

##Shows heteroscedasticity

#Assumption 1.4: Normality of residuals

shapiro.test(pop_farming$residuals)

##Normality of residuals met

#Overall the model does not work with Nairobi in it


```

```{r H1, linear regression model 2}
#Assumption 2.1: Normality

counties_data_no_capital <- counties_data |> 
  filter(County != "Nairobi City")

shapiro.test(counties_data_no_capital$Population)
hist(counties_data_no_capital$Population)

##Removing Nairobi results in a normal population distribution

pop_farming_no_capital <- lm(Farming ~ Population, data = counties_data_no_capital)
glance(pop_farming_no_capital)

#Assumption 2.2: Linearity

raintest(pop_farming_no_capital)

##Shows linearity

#Assumption 2.3: Homoscedasticity

bptest(pop_farming_no_capital)

##Still shows heteroscedasticity

#Assumption 2.4: Normality of residuals

shapiro.test(pop_farming_no_capital$residuals)

##Normality of residuals not met

##This model is still not sufficient, but it massively improves explanatory or predictive power, as can be seen by the R2 value.

```

```{r H1, robust regression}

#Final model

##Using the data without Nairobi so linearity is met

bc <- boxcox(Farming ~ Population, data = counties_data_no_capital)
lambda <- bc$x[which.max(bc$y)]


box_cox_model <- lmrob(((Farming^lambda-1)/lambda) ~ Population, data = counties_data_no_capital)

qqnorm(box_cox_model$residuals)

#Box-Cox transformation



#Huber regression
box_cox_model <- lmrob(Farming ~ Population, data = counties_data_no_capital_sqrt)
summary(box_cox_model)

#Assumption 3.1: Normality of residuals

shapiro.test(box_cox_model$residuals)

##Assumption not met

#Assumption 3.2: Linearity

raintest(box_cox_model)

#Assumption met

#Assumption 3.3: Homoscedasticity

bptest(box_cox_model)

#Assumption not met

#Furthermore, robust regression is not suitable for less than 100 observations
```

In conclusion, there are too many issues with the data to create a reliable regression between population and farming, especially because of the issue of nonlinearity.

```{r H2}
##H2: Is there a positive correlation between Tea and Coffee production?

cor(counties_data_no_capital$Tea, counties_data_no_capital$Coffee, use = "pairwise.complete.obs")

counties_data_no_capital |> 
  ggplot(aes(x = Tea, y = Coffee)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Tea and Coffee Production",
    x = "Tea",
    y = "Coffee"
  ) +
  theme_minimal()

tea_model <- lm(Tea ~ Coffee, data = counties_data_no_capital)

#Assumption 4.1: Normality

shapiro.test(counties_data_no_capital$Tea)
##Normality not met

counties_data_no_capital_log <- counties_data_no_capital |> 
  mutate(Tea = log(Tea),
         Coffee = log(Coffee))

shapiro.test(counties_data_no_capital_log$Tea)

#Normality met

tea_model <- lm(Tea ~ Coffee, data = counties_data_no_capital_log)

#Assumption 4.2: Linearity

raintest(tea_model)

##Linearity met

#Assumption 4.3: Homoscedasticity

bptest(tea_model)

##Homoscedasticity met

#Assumption 4.4: Normality of residuals

shapiro.test(tea_model$residuals)

##Normality of residuals met

#All asumptions met

glance(tea_model)
summary(tea_model)

```

```{r H2 tables}
library(apaTables)
apa_table <- apa.reg.table(tea_model)
print(apa_table)

library(rempsyc)

stats.table <- as.data.frame(summary(tea_model)$coefficients)

CI <- confint(tea_model)

stats.table <- cbind(row.names(stats.table), stats.table, CI)

names(stats.table) <- c("Variable", "Estimate", "Std. Error", "t-value", "p", "CI_lower", "CI_upper")

nice_table(stats.table, highlight = .05)


#Issues: no R2, no asterisk next to p value, no Notes. section
```

```{r H3, Mediation analysis}
#H3: Farming is a mediator between population and average household size

cor(counties_data_no_capital$Population, counties_data_no_capital$Farming, use = "pairwise.complete.obs")
cor(counties_data_no_capital$Population, counties_data_no_capital$AverageHouseholdSize, use = "pairwise.complete.obs")
cor(counties_data_no_capital$Farming, counties_data_no_capital$AverageHouseholdSize, use = "pairwise.complete.obs")



mediate_model <- lm(Farming ~ Population, data = counties_data_no_capital)
summary(mediate_model)
full_model <- lm(AverageHouseholdSize ~ Population + Farming, data = counties_data_no_capital)
summary(full_model)
results <- mediate(mediate_model, full_model, treat = "Population", mediator = "Farming", robustSE = TRUE, sims = 1000)
summary(results)

mediate_plot(AverageHouseholdSize ~ Population + Farming, data = counties_data_no_capital, mediator = Farming, method = "lm")
```

